# Set up navigation: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
site_name: mllibs
repo_name: 'mllibs'
repo_url: https://github.com/shtrausslearning/mllibs
edit_uri: tree/master/docs/src/markdown
site_description: Reference for mllibs
docs_dir: markdown

##################################################################

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight   
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - meta
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - toc:
      baselevel: 2
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


##################################################################

theme:
    name: material
    icon:
        logo: fontawesome/solid/code 
        repo: fontawesome/brands/github
    language: en
    features:
        - navigation.instant
        - navigation.instant.progress
        - navigation.sections
        # - navigation.expand
        - navigation.tracking
        - navigation.top
        - content.tabs.link

    palette:
        - scheme: slate

    # font:
        # text: Ubuntu
        # code: Ubuntu Mono

extra:
    manifest: manifest.webmanifest

plugins:
    - search
    - tags
    - offline


copyright: |
  Copyright &copy; 2023 <a href="https://github.com/shtrausslearning"  target="_blank" rel="noopener">Andrey Shtrauss</a>

nav:
- home.md

- Installation: install.md

- Modules: 
    - Available modules: modules/list.md
    - Adding new modules: modules/adding.md
    - Grouping modules: modules/grouping.md

- Tutorials: 
    - Overview: tutorials/overview.md

- Documentation: 
    - nlpm: documentation/nlpm.md
    - nlpi: documentation/nlpi.md

- Group:
    - Task Status: group/status.md
    - Meetings: group/meetups.md
    - Members: group/members.md
